name: Run update pipeline

on:
  workflow_dispatch:

jobs:
  run-script:
    runs-on:
      group: Default
      labels: [self-hosted, linux, ubuntu-server-2404]

    defaults:
      run:
        shell: bash

    steps:
      - name: Show current directory
        run: pwd

      - name: Make script executable
        run: chmod +x /home/ubuntu-runner/update_pipeline.sh

      - name: Run update script
        run: /home/ubuntu-runner/update_pipeline.sh