name: Run update pipeline

on:
  workflow_dispatch:

jobs:
  run-update:
    uses: ./.github/workflows/update_pipeline_template.yml
    with:
      web_server: 172.16.1.10
      web_path: /var/www/html
      deploy_user: student
      public_key_path: /home/github-runner/public.key
      workdir_base: /home/github-runner/update-workdir
      gpg_fingerprint: ""
      ssh_known_hosts: ""
      enable_verification: false