name: Run update pipeline

on:
  workflow_dispatch:

jobs:
  run-script:
    runs-on: [self-hosted, linux]

    defaults:
      run:
        shell: bash

    steps:
      - name: Show current directory
        run: pwd

      - name: Run update script
        run: bash /home/github-runner/update_pipeline.sh